name: pull-request
on: [pull_request]

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
      - run: npm ci
      - name: Run ESLint
        uses: reviewdog/action-eslint@v1
        with:
        reporter: github-check
        eslint_flags: "src/"
        fail_on_error: true
